services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-cicd
    ports:
      - 9091:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - cicd-network
      - jenkins

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-cicd
    ports:
      - 3001:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/etc/grafana/dashboards/
    networks:
      - cicd-network

networks:
  cicd-network:
    driver: bridge
  jenkins:
    external: true

volumes:
  grafana_data:
  prometheus_data: