pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
        NODE_OPTIONS = '--openssl-legacy-provider'
        HEROKU_API_KEY = credentials('heroku-api-key')
        HEROKU_APP_NAME = 'cicd-app'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deploy to Heroku') {
            input {
                message 'Lanjutkan ke stage Deploy?'
                ok 'Lanjutkan'
            }
            steps {
                sh '''
                    apt-get update && apt-get install -y git
                    git remote remove heroku || true
                    git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git
                    git push heroku HEAD:main --force
                '''
            }
        }
    }
}
